// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu-ZD4TCb_fajPVNyCdKkigcqLYKIaPjs',
    appId: '1:1027504610760:web:c64696bbee9e63de37f4fd',
    messagingSenderId: '1027504610760',
    projectId: 'lab12-d8166',
    authDomain: 'lab12-d8166.firebaseapp.com',
    storageBucket: 'lab12-d8166.firebasestorage.app',
    measurementId: 'G-GVC3B2KXZN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDokWAEammXOAyow94XdZ-CC1N6u_mCJ1k',
    appId: '1:1027504610760:android:910e8ba49a45f41737f4fd',
    messagingSenderId: '1027504610760',
    projectId: 'lab12-d8166',
    storageBucket: 'lab12-d8166.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZPyJr8HHsV9ormuNJPqeT7ryUOc6yIOk',
    appId: '1:1027504610760:ios:94222648d683100737f4fd',
    messagingSenderId: '1027504610760',
    projectId: 'lab12-d8166',
    storageBucket: 'lab12-d8166.firebasestorage.app',
    iosBundleId: 'com.example.rideSharingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZPyJr8HHsV9ormuNJPqeT7ryUOc6yIOk',
    appId: '1:1027504610760:ios:94222648d683100737f4fd',
    messagingSenderId: '1027504610760',
    projectId: 'lab12-d8166',
    storageBucket: 'lab12-d8166.firebasestorage.app',
    iosBundleId: 'com.example.rideSharingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCu-ZD4TCb_fajPVNyCdKkigcqLYKIaPjs',
    appId: '1:1027504610760:web:4e79c47167be93ab37f4fd',
    messagingSenderId: '1027504610760',
    projectId: 'lab12-d8166',
    authDomain: 'lab12-d8166.firebaseapp.com',
    storageBucket: 'lab12-d8166.firebasestorage.app',
    measurementId: 'G-FKRWQYX4LN',
  );
}
